### ISSUE TITLE
css/styling

### ISSUE THREAD

**Issue by mrndlng** [VCUarts/arts-research-institute#10]
OVERALL
- [x] when screen width is less than 1555 px, search bar and buttons in header overlap
- [x] underline to indicate active page in spine nav extends too far left:
![screen shot 2017-07-07 at 12 27 53 pm](https://user-images.githubusercontent.com/19610484/27967097-ba7491f2-630f-11e7-9016-57ccffcc8711.png)

PROJECTS — GRID PAGE
![screen shot 2017-07-07 at 12 29 01 pm](https://user-images.githubusercontent.com/19610484/27967158-f62975b4-630f-11e7-878d-60c565a97e30.png)
![screen shot 2017-07-07 at 12 11 13 pm](https://user-images.githubusercontent.com/19610484/27966492-69bbe03c-630d-11e7-9b4c-3a307541736e.png)
- [x] on hover, every project image besides the one that's being selected should transform to grayscale and the selected project div background color should be green ( #F0FFF8 ) like the reference pic above
- [x] there should be more spacing (padding?) inside each box around the text (~38 px)
- [x] project title font size should be smaller, like 30 px
- [x] project title weight should be bold

CONNECT PAGE 
![screen shot 2017-07-07 at 12 29 09 pm](https://user-images.githubusercontent.com/19610484/27967153-efbb6020-630f-11e7-8fe9-438f81938f67.png)

- [x] Our Mission body text is in two different styles right now; should just be one (Aktiv Grotesk Light)
- [x] Our Mission body text letter spacing should be smaller (like .08 em)

**Comment by streeetlamp** [comment]
8/8?? closed !
