### ISSUE TITLE
Sidebar / Nav

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/arts-research-institute#4]
Need this dude 

![screen shot 2017-04-17 at 1 19 08 pm](https://cloud.githubusercontent.com/assets/1740634/25096964/7f5efcee-2370-11e7-961e-cc2607325530.png)

So

- [x] Menu
- [x] Social Link
- [x] Contact Info

**Comment by bzkn** [comment]
added social and link content, will do styling next

- [ ] styling for social links
- [ ] styling for contact info

**Comment by streeetlamp** [comment]
will open new sidebar issues as needed
